/**
 * Country currency list based on ISO-4217, contain
 * - country name
 * - currency name
 * - currency alphabetical code
 * - currency numeric code
 * - currency minor digits for round sum
 * @type {{country: String, currency: String, alpha3: String, numeric: String, minor: Number}[]}
 */
const list = [
    {
        country: 'Afghanistan',
        currency: 'Afghani',
        alpha3: 'AFN',
        numeric: '971',
        minor: 2,
    },
    {
        country: 'Aland Islands',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Albania',
        currency: 'Lek',
        alpha3: 'ALL',
        numeric: '008',
        minor: 2,
    },
    {
        country: 'Algeria',
        currency: 'Algerian Dinar',
        alpha3: 'DZD',
        numeric: '012',
        minor: 2,
    },
    {
        country: 'American Samoa',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Andorra',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Angola',
        currency: 'Kwanza',
        alpha3: 'AOA',
        numeric: '973',
        minor: 2,
    },
    {
        country: 'Anguilla',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Antigua And Barbuda',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Argentina',
        currency: 'Argentine Peso',
        alpha3: 'ARS',
        numeric: '032',
        minor: 2,
    },
    {
        country: 'Armenia',
        currency: 'Armenian Dram',
        alpha3: 'AMD',
        numeric: '051',
        minor: 2,
    },
    {
        country: 'Aruba',
        currency: 'Aruban Florin',
        alpha3: 'AWG',
        numeric: '533',
        minor: 2,
    },
    {
        country: 'Australia',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Austria',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Azerbaijan',
        currency: 'Azerbaijan Manat',
        alpha3: 'AZN',
        numeric: '944',
        minor: 2,
    },
    {
        country: 'Bahamas (The)',
        currency: 'Bahamian Dollar',
        alpha3: 'BSD',
        numeric: '044',
        minor: 2,
    },
    {
        country: 'Bahrain',
        currency: 'Bahraini Dinar',
        alpha3: 'BHD',
        numeric: '048',
        minor: 3,
    },
    {
        country: 'Bangladesh',
        currency: 'Taka',
        alpha3: 'BDT',
        numeric: '050',
        minor: 2,
    },
    {
        country: 'Barbados',
        currency: 'Barbados Dollar',
        alpha3: 'BBD',
        numeric: '052',
        minor: 2,
    },
    {
        country: 'Belarus',
        currency: 'Belarusian Ruble',
        alpha3: 'BYN',
        numeric: '933',
        minor: 2,
    },
    {
        country: 'Belgium',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Belize',
        currency: 'Belize Dollar',
        alpha3: 'BZD',
        numeric: '084',
        minor: 2,
    },
    {
        country: 'Benin',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Bermuda',
        currency: 'Bermudian Dollar',
        alpha3: 'BMD',
        numeric: '060',
        minor: 2,
    },
    {
        country: 'Bhutan',
        currency: 'Indian Rupee',
        alpha3: 'INR',
        numeric: '356',
        minor: 2,
    },
    {
        country: 'Bhutan',
        currency: 'Ngultrum',
        alpha3: 'BTN',
        numeric: '064',
        minor: 2,
    },
    {
        country: 'Bolivia (Plurinational State Of)',
        currency: 'Boliviano',
        alpha3: 'BOB',
        numeric: '068',
        minor: 2,
    },
    {
        country: 'Bolivia (Plurinational State Of)',
        currency: 'Mvdol',
        alpha3: 'BOV',
        numeric: '984',
        minor: 2,
    },
    {
        country: 'Bonaire, Sint Eustatius And Saba',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Bosnia And Herzegovina',
        currency: 'Convertible Mark',
        alpha3: 'BAM',
        numeric: '977',
        minor: 2,
    },
    {
        country: 'Botswana',
        currency: 'Pula',
        alpha3: 'BWP',
        numeric: '072',
        minor: 2,
    },
    {
        country: 'Bouvet Island',
        currency: 'Norwegian Krone',
        alpha3: 'NOK',
        numeric: '578',
        minor: 2,
    },
    {
        country: 'Brazil',
        currency: 'Brazilian Real',
        alpha3: 'BRL',
        numeric: '986',
        minor: 2,
    },
    {
        country: 'British Indian Ocean Territory (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Brunei Darussalam',
        currency: 'Brunei Dollar',
        alpha3: 'BND',
        numeric: '096',
        minor: 2,
    },
    {
        country: 'Bulgaria',
        currency: 'Bulgarian Lev',
        alpha3: 'BGN',
        numeric: '975',
        minor: 2,
    },
    {
        country: 'Burkina Faso',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Burundi Burundi',
        currency: 'Franc',
        alpha3: 'BIF',
        numeric: '108',
        minor: 0,
    },
    {
        country: 'Cabo Verde',
        currency: 'Cabo Verde Escudo',
        alpha3: 'CVE',
        numeric: '132',
        minor: 2,
    },
    {
        country: 'Cambodia',
        currency: 'Riel',
        alpha3: 'KHR',
        numeric: '116',
        minor: 2,
    },
    {
        country: 'Cameroon',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Canada',
        currency: 'Canadian Dollar',
        alpha3: 'CAD',
        numeric: '124',
        minor: 2,
    },
    {
        country: 'Cayman Islands (The)',
        currency: 'Cayman Islands Dollar',
        alpha3: 'KYD',
        numeric: '136',
        minor: 2,
    },
    {
        country: 'Central African Republic (The)',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Chad',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Chile',
        currency: 'Chilean Peso',
        alpha3: 'CLP',
        numeric: '152',
        minor: 0,
    },
    {
        country: 'Chile',
        currency: 'Unidad de Fomento',
        alpha3: 'CLF',
        numeric: '990',
        minor: 4,
    },
    {
        country: 'China',
        currency: 'Yuan Renminbi',
        alpha3: 'CNY',
        numeric: '156',
        minor: 2,
    },
    {
        country: 'Christmas Island',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Cocos (KEELING) Islands (The)',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Colombia',
        currency: 'Colombian Peso',
        alpha3: 'COP',
        numeric: '170',
        minor: 2,
    },
    {
        country: 'Colombia',
        currency: 'Unidad de Valor Real',
        alpha3: 'COU',
        numeric: '970',
        minor: 2,
    },
    {
        country: 'Comoros (The)',
        currency: 'Comorian Franc',
        alpha3: 'KMF',
        numeric: '174',
        minor: 0,
    },
    {
        country: 'Congo (The Democratic Republic Of The)',
        currency: 'Congolese Franc',
        alpha3: 'CDF',
        numeric: '976',
        minor: 2,
    },
    {
        country: 'Congo (The)',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Cook Islands (The)',
        currency: 'New Zealand Dollar',
        alpha3: 'NZD',
        numeric: '554',
        minor: 2,
    },
    {
        country: 'Costa Rica',
        currency: 'Costa Rican Colon',
        alpha3: 'CRC',
        numeric: '188',
        minor: 2,
    },
    {
        country: 'Cote d\'Ivoire',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Croatia',
        currency: 'Kuna',
        alpha3: 'HRK',
        numeric: '191',
        minor: 2,
    },
    {
        country: 'Cuba',
        currency: 'Cuban Peso',
        alpha3: 'CUP',
        numeric: '192',
        minor: 2,
    },
    {
        country: 'Cuba',
        currency: 'Peso Convertible',
        alpha3: 'CUC',
        numeric: '931',
        minor: 2,
    },
    {
        country: 'Curacao',
        currency: 'Netherlands Antillean Guilder',
        alpha3: 'ANG',
        numeric: '532',
        minor: 2,
    },
    {
        country: 'Cyprus',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Czechia',
        currency: 'Czech Koruna',
        alpha3: 'CZK',
        numeric: '203',
        minor: 2,
    },
    {
        country: 'Denmark',
        currency: 'Danish Krone',
        alpha3: 'DKK',
        numeric: '208',
        minor: 2,
    },
    {
        country: 'Djibouti',
        currency: 'Djibouti Franc',
        alpha3: 'DJF',
        numeric: '262',
        minor: 0,
    },
    {
        country: 'Dominica',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Dominican Republic (The)',
        currency: 'Dominican Peso',
        alpha3: 'DOP',
        numeric: '214',
        minor: 2,
    },
    {
        country: 'Ecuador',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Egypt',
        currency: 'Egyptian Pound',
        alpha3: 'EGP',
        numeric: '818',
        minor: 2,
    },
    {
        country: 'El Salvador',
        currency: 'El Salvador Colon',
        alpha3: 'SVC',
        numeric: '222',
        minor: 2,
    },
    {
        country: 'El Salvador',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Equatorial Guinea',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Eritrea',
        currency: 'Nakfa',
        alpha3: 'ERN',
        numeric: '232',
        minor: 2,
    },
    {
        country: 'Estonia',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Ethiopia',
        currency: 'Ethiopian Birr',
        alpha3: 'ETB',
        numeric: '230',
        minor: 2,
    },
    {
        country: 'European Union',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Falkland Islands (The) [Malvinas]',
        currency: 'Falkland Islands Pound',
        alpha3: 'FKP',
        numeric: '238',
        minor: 2,
    },
    {
        country: 'Faroe Islands (The)',
        currency: 'Danish Krone',
        alpha3: 'DKK',
        numeric: '208',
        minor: 2,
    },
    {
        country: 'Fiji',
        currency: 'Fiji Dollar',
        alpha3: 'FJD',
        numeric: '242',
        minor: 2,
    },
    {
        country: 'Finland',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'France',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'French Guiana',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'French Polynesia',
        currency: 'CFP Franc',
        alpha3: 'XPF',
        numeric: '953',
        minor: 0,
    },
    {
        country: 'French Southern Territories (The)',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Gabon',
        currency: 'CFA Franc BEAC',
        alpha3: 'XAF',
        numeric: '950',
        minor: 0,
    },
    {
        country: 'Gambia (The)',
        currency: 'Dalasi',
        alpha3: 'GMD',
        numeric: '270',
        minor: 2,
    },
    {
        country: 'Georgia',
        currency: 'Lari',
        alpha3: 'GEL',
        numeric: '981',
        minor: 2,
    },
    {
        country: 'Germany',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Ghana',
        currency: 'Ghana Cedi',
        alpha3: 'GHS',
        numeric: '936',
        minor: 2,
    },
    {
        country: 'Gibraltar',
        currency: 'Gibraltar Pound',
        alpha3: 'GIP',
        numeric: '292',
        minor: 2,
    },
    {
        country: 'Greece',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Greenland',
        currency: 'Danish Krone',
        alpha3: 'DKK',
        numeric: '208',
        minor: 2,
    },
    {
        country: 'Grenada',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Guadeloupe',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Guam',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Guatemala',
        currency: 'Quetzal',
        alpha3: 'GTQ',
        numeric: '320',
        minor: 2,
    },
    {
        country: 'Guernsey',
        currency: 'Pound Sterling',
        alpha3: 'GBP',
        numeric: '826',
        minor: 2,
    },
    {
        country: 'Guinea',
        currency: 'Guinean Franc',
        alpha3: 'GNF',
        numeric: '324',
        minor: 0,
    },
    {
        country: 'Guinea-Bissau',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Guyana',
        currency: 'Guyana Dollar',
        alpha3: 'GYD',
        numeric: '328',
        minor: 2,
    },
    {
        country: 'Haiti',
        currency: 'Gourde',
        alpha3: 'HTG',
        numeric: '332',
        minor: 2,
    },
    {
        country: 'Haiti',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Heard Island And Mcdonald Islands',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Holy See (The)',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Honduras',
        currency: 'Lempira',
        alpha3: 'HNL',
        numeric: '340',
        minor: 2,
    },
    {
        country: 'Hong Kong',
        currency: 'Hong Kong Dollar',
        alpha3: 'HKD',
        numeric: '344',
        minor: 2,
    },
    {
        country: 'Hungary',
        currency: 'Forint',
        alpha3: 'HUF',
        numeric: '348',
        minor: 2,
    },
    {
        country: 'Iceland',
        currency: 'Iceland Krona',
        alpha3: 'ISK',
        numeric: '352',
        minor: 0,
    },
    {
        country: 'India',
        currency: 'Indian Rupee',
        alpha3: 'INR',
        numeric: '356',
        minor: 2,
    },
    {
        country: 'Indonesia',
        currency: 'Rupiah',
        alpha3: 'IDR',
        numeric: '360',
        minor: 2,
    },
    {
        country: 'International Monetary Fund (IMF)',
        currency: 'SDR (Special Drawing Right',
        alpha3: 'XDR',
        numeric: '960',
        minor: 0,
    },
    {
        country: 'Iran (Islamic Republic Of)',
        currency: 'Iranian Rial',
        alpha3: 'IRR',
        numeric: '364',
        minor: 2,
    },
    {
        country: 'Iraq',
        currency: 'Iraqi Dinar',
        alpha3: 'IQD',
        numeric: '368',
        minor: 3,
    },
    {
        country: 'Ireland',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Isle Of Man',
        currency: 'Pound Sterling',
        alpha3: 'GBP',
        numeric: '826',
        minor: 2,
    },
    {
        country: 'Israel',
        currency: 'New Israeli Sheqel',
        alpha3: 'ILS',
        numeric: '376',
        minor: 2,
    },
    {
        country: 'Italy',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Jamaica',
        currency: 'Jamaican Dollar',
        alpha3: 'JMD',
        numeric: '388',
        minor: 2,
    },
    {
        country: 'Japan',
        currency: 'Yen',
        alpha3: 'JPY',
        numeric: '392',
        minor: 0,
    },
    {
        country: 'Jersey',
        currency: 'Pound Sterling',
        alpha3: 'GBP',
        numeric: '826',
        minor: 2,
    },
    {
        country: 'Jordan',
        currency: 'Jordanian Dinar',
        alpha3: 'JOD',
        numeric: '400',
        minor: 3,
    },
    {
        country: 'Kazakhstan',
        currency: 'Tenge',
        alpha3: 'KZT',
        numeric: '398',
        minor: 2,
    },
    {
        country: 'Kenya',
        currency: 'Kenyan Shilling',
        alpha3: 'KES',
        numeric: '404',
        minor: 2,
    },
    {
        country: 'Kiribati',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Korea (The Democratic People’s Republic Of)',
        currency: 'North Korean Won',
        alpha3: 'KPW',
        numeric: '408',
        minor: 2,
    },
    {
        country: 'Korea (The Republic Of)',
        currency: 'Won',
        alpha3: 'KRW',
        numeric: '410',
        minor: 0,
    },
    {
        country: 'Kuwait',
        currency: 'Kuwaiti Dinar',
        alpha3: 'KWD',
        numeric: '414',
        minor: 3,
    },
    {
        country: 'Kyrgyzstan',
        currency: 'Som',
        alpha3: 'KGS',
        numeric: '417',
        minor: 2,
    },
    {
        country: 'Lao People’s Democratic Republic (The)',
        currency: 'Lao Kip',
        alpha3: 'LAK',
        numeric: '418',
        minor: 2,
    },
    {
        country: 'Latvia',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Lebanon',
        currency: 'Lebanese Pound',
        alpha3: 'LBP',
        numeric: '422',
        minor: 2,
    },
    {
        country: 'Lesotho',
        currency: 'Loti',
        alpha3: 'LSL',
        numeric: '426',
        minor: 2,
    },
    {
        country: 'Lesotho',
        currency: 'Rand',
        alpha3: 'ZAR',
        numeric: '710',
        minor: 2,
    },
    {
        country: 'Liberia',
        currency: 'Liberian Dollar',
        alpha3: 'LRD',
        numeric: '430',
        minor: 2,
    },
    {
        country: 'Libya',
        currency: 'Libyan Dinar',
        alpha3: 'LYD',
        numeric: '434',
        minor: 3,
    },
    {
        country: 'Liechtenstein',
        currency: 'Swiss Franc',
        alpha3: 'CHF',
        numeric: '756',
        minor: 2,
    },
    {
        country: 'Lithuania',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Luxembourg',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Macao',
        currency: 'Pataca',
        alpha3: 'MOP',
        numeric: '446',
        minor: 2,
    },
    {
        country: 'Macedonia (The Former Yugoslav Republic Of)',
        currency: 'Denar',
        alpha3: 'MKD',
        numeric: '807',
        minor: 2,
    },
    {
        country: 'Madagascar',
        currency: 'Malagasy Ariary',
        alpha3: 'MGA',
        numeric: '969',
        minor: 2,
    },
    {
        country: 'Malawi',
        currency: 'Malawi Kwacha',
        alpha3: 'MWK',
        numeric: '454',
        minor: 2,
    },
    {
        country: 'Malaysia',
        currency: 'Malaysian Ringgit',
        alpha3: 'MYR',
        numeric: '458',
        minor: 2,
    },
    {
        country: 'Maldives',
        currency: 'Rufiyaa',
        alpha3: 'MVR',
        numeric: '462',
        minor: 2,
    },
    {
        country: 'Mali',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Malta',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Marshall Islands (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Martinique',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Mauritania',
        currency: 'Ouguiya',
        alpha3: 'MRO',
        numeric: '478',
        minor: 2,
    },
    {
        country: 'Mauritius',
        currency: 'Mauritius Rupee',
        alpha3: 'MUR',
        numeric: '480',
        minor: 2,
    },
    {
        country: 'Mayotte',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Member Countries Of The African Development Bank Group',
        currency: 'ADB Unit of Account',
        alpha3: 'XUA',
        numeric: '965',
        minor: 0,
    },
    {
        country: 'Mexico',
        currency: 'Mexican Peso',
        alpha3: 'MXN',
        numeric: '484',
        minor: 2,
    },
    {
        country: 'Mexico',
        currency: 'Mexican Unidad de Inversion (UDI)',
        alpha3: 'MXV',
        numeric: '979',
        minor: 2,
    },
    {
        country: 'Micronesia (FEDERATED States Of)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Moldova (The Republic Of)',
        currency: 'Moldovan Leu',
        alpha3: 'MDL',
        numeric: '498',
        minor: 2,
    },
    {
        country: 'Monaco',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Mongolia',
        currency: 'Tugrik',
        alpha3: 'MNT',
        numeric: '496',
        minor: 2,
    },
    {
        country: 'Montenegro',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Montserrat',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Morocco',
        currency: 'Moroccan Dirham',
        alpha3: 'MAD',
        numeric: '504',
        minor: 2,
    },
    {
        country: 'Mozambique',
        currency: 'Mozambique Metical',
        alpha3: 'MZN',
        numeric: '943',
        minor: 2,
    },
    {
        country: 'Myanmar',
        currency: 'Kyat',
        alpha3: 'MMK',
        numeric: '104',
        minor: 2,
    },
    {
        country: 'Namibia',
        currency: 'Namibia Dollar',
        alpha3: 'NAD',
        numeric: '516',
        minor: 2,
    },
    {
        country: 'Namibia',
        currency: 'Rand',
        alpha3: 'ZAR',
        numeric: '710',
        minor: 2,
    },
    {
        country: 'Nauru',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Nepal',
        currency: 'Nepalese Rupee',
        alpha3: 'NPR',
        numeric: '524',
        minor: 2,
    },
    {
        country: 'Netherlands (The)',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'New Caledonia',
        currency: 'CFP Franc',
        alpha3: 'XPF',
        numeric: '953',
        minor: 0,
    },
    {
        country: 'New Zealand',
        currency: 'New Zealand Dollar',
        alpha3: 'NZD',
        numeric: '554',
        minor: 2,
    },
    {
        country: 'Nicaragua',
        currency: 'Cordoba Oro',
        alpha3: 'NIO',
        numeric: '558',
        minor: 2,
    },
    {
        country: 'Niger (The)',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Nigeria',
        currency: 'Naira',
        alpha3: 'NGN',
        numeric: '566',
        minor: 2,
    },
    {
        country: 'Niue',
        currency: 'New Zealand Dollar',
        alpha3: 'NZD',
        numeric: '554',
        minor: 2,
    },
    {
        country: 'Norfolk Island',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Northern Mariana Islands (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Norway',
        currency: 'Norwegian Krone',
        alpha3: 'NOK',
        numeric: '578',
        minor: 2,
    },
    {
        country: 'Oman',
        currency: 'Rial Omani',
        alpha3: 'OMR',
        numeric: '512',
        minor: 3,
    },
    {
        country: 'Pakistan',
        currency: 'Pakistan Rupee',
        alpha3: 'PKR',
        numeric: '586',
        minor: 2,
    },
    {
        country: 'Palau',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Panama',
        currency: 'Balboa',
        alpha3: 'PAB',
        numeric: '590',
        minor: 2,
    },
    {
        country: 'Panama',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Papua New Guinea',
        currency: 'Kina',
        alpha3: 'PGK',
        numeric: '598',
        minor: 2,
    },
    {
        country: 'Paraguay',
        currency: 'Guarani',
        alpha3: 'PYG',
        numeric: '600',
        minor: 0,
    },
    {
        country: 'Peru',
        currency: 'Sol',
        alpha3: 'PEN',
        numeric: '604',
        minor: 2,
    },
    {
        country: 'Philippines (The)',
        currency: 'Philippine Piso',
        alpha3: 'PHP',
        numeric: '608',
        minor: 2,
    },
    {
        country: 'Pitcairn',
        currency: 'New Zealand Dollar',
        alpha3: 'NZD',
        numeric: '554',
        minor: 2,
    },
    {
        country: 'Poland',
        currency: 'Zloty',
        alpha3: 'PLN',
        numeric: '985',
        minor: 2,
    },
    {
        country: 'Portugal',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Puerto Rico',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Qatar',
        currency: 'Qatari Rial',
        alpha3: 'QAR',
        numeric: '634',
        minor: 2,
    },
    {
        country: 'Réunion',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Romania',
        currency: 'Romanian Leu',
        alpha3: 'RON',
        numeric: '946',
        minor: 2,
    },
    {
        country: 'Russian Federation (The)',
        currency: 'Russian Ruble',
        alpha3: 'RUB',
        numeric: '643',
        minor: 2,
    },
    {
        country: 'Rwanda',
        currency: 'Rwanda Franc',
        alpha3: 'RWF',
        numeric: '646',
        minor: 0,
    },
    {
        country: 'Saint Barthelemy',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Saint Helena, Ascension And Tristan Da Cunha',
        currency: 'Saint Helena Pound',
        alpha3: 'SHP',
        numeric: '654',
        minor: 2,
    },
    {
        country: 'Saint Kitts And Nevis',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Saint Lucia',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Saint Martin (French Part)',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Saint Pierre And Miquelon',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Saint Vincent And The Grenadines',
        currency: 'East Caribbean Dollar',
        alpha3: 'XCD',
        numeric: '951',
        minor: 2,
    },
    {
        country: 'Samoa',
        currency: 'Tala',
        alpha3: 'WST',
        numeric: '882',
        minor: 2,
    },
    {
        country: 'San Marino',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Sao Tome And Principe',
        currency: 'Dobra',
        alpha3: 'STD',
        numeric: '678',
        minor: 2,
    },
    {
        country: 'Saudi Arabia',
        currency: 'Saudi Riyal',
        alpha3: 'SAR',
        numeric: '682',
        minor: 2,
    },
    {
        country: 'Senegal',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Serbia',
        currency: 'Serbian Dinar',
        alpha3: 'RSD',
        numeric: '941',
        minor: 2,
    },
    {
        country: 'Seychelles',
        currency: 'Seychelles Rupee',
        alpha3: 'SCR',
        numeric: '690',
        minor: 2,
    },
    {
        country: 'Sierra Leone',
        currency: 'Leone',
        alpha3: 'SLL',
        numeric: '694',
        minor: 2,
    },
    {
        country: 'Singapore',
        currency: 'Singapore Dollar',
        alpha3: 'SGD',
        numeric: '702',
        minor: 2,
    },
    {
        country: 'Sint Maarten (Dutch Part)',
        currency: 'Netherlands Antillean Guilder',
        alpha3: 'ANG',
        numeric: '532',
        minor: 2,
    },
    {
        country: 'Sistema Unitario De Compensacion Regional De Pagos "Sucre"',
        currency: 'Sucre',
        alpha3: 'XSU',
        numeric: '994',
        minor: 0,
    },
    {
        country: 'Slovakia',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Slovenia',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Solomon Islands',
        currency: 'Solomon Islands Dollar',
        alpha3: 'SBD',
        numeric: '090',
        minor: 2,
    },
    {
        country: 'Somalia',
        currency: 'Somali Shilling',
        alpha3: 'SOS',
        numeric: '706',
        minor: 2,
    },
    {
        country: 'South Africa',
        currency: 'Rand',
        alpha3: 'ZAR',
        numeric: '710',
        minor: 2,
    },
    {
        country: 'South Sudan',
        currency: 'South Sudanese Pound',
        alpha3: 'SSP',
        numeric: '728',
        minor: 2,
    },
    {
        country: 'Spain',
        currency: 'Euro',
        alpha3: 'EUR',
        numeric: '978',
        minor: 2,
    },
    {
        country: 'Sri Lanka',
        currency: 'Sri Lanka Rupee',
        alpha3: 'LKR',
        numeric: '144',
        minor: 2,
    },
    {
        country: 'Sudan (The)',
        currency: 'Sudanese Pound',
        alpha3: 'SDG',
        numeric: '938',
        minor: 2,
    },
    {
        country: 'Suriname',
        currency: 'Surinam Dollar',
        alpha3: 'SRD',
        numeric: '968',
        minor: 2,
    },
    {
        country: 'Svalbard And Jan Mayen',
        currency: 'Norwegian Krone',
        alpha3: 'NOK',
        numeric: '578',
        minor: 2,
    },
    {
        country: 'Swaziland',
        currency: 'Lilangeni',
        alpha3: 'SZL',
        numeric: '748',
        minor: 2,
    },
    {
        country: 'Sweden',
        currency: 'Swedish Krona',
        alpha3: 'SEK',
        numeric: '752',
        minor: 2,
    },
    {
        country: 'Switzerland',
        currency: 'Swiss Franc',
        alpha3: 'CHF',
        numeric: '756',
        minor: 2,
    },
    {
        country: 'Switzerland',
        currency: 'WIR Euro',
        alpha3: 'CHE',
        numeric: '947',
        minor: 2,
    },
    {
        country: 'Switzerland',
        currency: 'WIR Franc',
        alpha3: 'CHW',
        numeric: '948',
        minor: 2,
    },
    {
        country: 'Syrian Arab Republic',
        currency: 'Syrian Pound',
        alpha3: 'SYP',
        numeric: '760',
        minor: 2,
    },
    {
        country: 'Taiwan (PROVINCE Of China)',
        currency: 'New Taiwan Dollar',
        alpha3: 'TWD',
        numeric: '901',
        minor: 2,
    },
    {
        country: 'Tajikistan',
        currency: 'Somoni',
        alpha3: 'TJS',
        numeric: '972',
        minor: 2,
    },
    {
        country: 'Tanzania, United Republic Of',
        currency: 'Tanzanian Shilling',
        alpha3: 'TZS',
        numeric: '834',
        minor: 2,
    },
    {
        country: 'Thailand',
        currency: 'Baht',
        alpha3: 'THB',
        numeric: '764',
        minor: 2,
    },
    {
        country: 'Timor-Leste',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Togo',
        currency: 'CFA Franc BCEAO',
        alpha3: 'XOF',
        numeric: '952',
        minor: 0,
    },
    {
        country: 'Tokelau',
        currency: 'New Zealand Dollar',
        alpha3: 'NZD',
        numeric: '554',
        minor: 2,
    },
    {
        country: 'Tonga',
        currency: 'Pa’anga',
        alpha3: 'TOP',
        numeric: '776',
        minor: 2,
    },
    {
        country: 'Trinidad And Tobago',
        currency: 'Trinidad and Tobago Dollar',
        alpha3: 'TTD',
        numeric: '780',
        minor: 2,
    },
    {
        country: 'Tunisia',
        currency: 'Tunisian Dinar',
        alpha3: 'TND',
        numeric: '788',
        minor: 3,
    },
    {
        country: 'Turkey',
        currency: 'Turkish Lira',
        alpha3: 'TRY',
        numeric: '949',
        minor: 2,
    },
    {
        country: 'Turkmenistan',
        currency: 'Turkmenistan New Manat',
        alpha3: 'TMT',
        numeric: '934',
        minor: 2,
    },
    {
        country: 'Turks And Caicos Islands (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Tuvalu',
        currency: 'Australian Dollar',
        alpha3: 'AUD',
        numeric: '036',
        minor: 2,
    },
    {
        country: 'Uganda',
        currency: 'Uganda Shilling',
        alpha3: 'UGX',
        numeric: '800',
        minor: 0,
    },
    {
        country: 'Ukraine',
        currency: 'Hryvnia',
        alpha3: 'UAH',
        numeric: '980',
        minor: 2,
    },
    {
        country: 'United Arab Emirates (The)',
        currency: 'UAE Dirham',
        alpha3: 'AED',
        numeric: '784',
        minor: 2,
    },
    {
        country: 'United Kingdom Of Great Britain And Northern Ireland (The)',
        currency: 'Pound Sterling',
        alpha3: 'GBP',
        numeric: '826',
        minor: 2,
    },
    {
        country: 'United States Minor Outlying Islands (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'United States Of America (The)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'United States Of America (The)',
        currency: 'US Dollar (Next day)',
        alpha3: 'USN',
        numeric: '997',
        minor: 2,
    },
    {
        country: 'Uruguay',
        currency: 'Peso Uruguayo',
        alpha3: 'UYU',
        numeric: '858',
        minor: 2,
    },
    {
        country: 'Uruguay',
        currency: 'Uruguay Peso en Unidades (Uruiurui)',
        alpha3: 'UYI',
        numeric: '940',
        minor: 0,
    },
    {
        country: 'Uzbekistan',
        currency: 'Uzbekistan Sum',
        alpha3: 'UZS',
        numeric: '860',
        minor: 2,
    },
    {
        country: 'Vanuatu',
        currency: 'Vatu',
        alpha3: 'VUV',
        numeric: '548',
        minor: 0,
    },
    {
        country: 'Venezuela (Bolivarian Republic Of)',
        currency: 'Bolívar',
        alpha3: 'VEF',
        numeric: '937',
        minor: 2,
    },
    {
        country: 'Viet Nam',
        currency: 'Dong',
        alpha3: 'VND',
        numeric: '704',
        minor: 0,
    },
    {
        country: 'Virgin Islands (British)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Virgin Islands (U.S.)',
        currency: 'US Dollar',
        alpha3: 'USD',
        numeric: '840',
        minor: 2,
    },
    {
        country: 'Wallis And Futuna',
        currency: 'CFP Franc',
        alpha3: 'XPF',
        numeric: '953',
        minor: 0,
    },
    {
        country: 'Western Sahara',
        currency: 'Moroccan Dirham',
        alpha3: 'MAD',
        numeric: '504',
        minor: 2,
    },
    {
        country: 'Yemen',
        currency: 'Yemeni Rial',
        alpha3: 'YER',
        numeric: '886',
        minor: 2,
    },
    {
        country: 'Zambia',
        currency: 'Zambian Kwacha',
        alpha3: 'ZMW',
        numeric: '967',
        minor: 2,
    },
    {
        country: 'Zimbabwe',
        currency: 'Zimbabwe Dollar',
        alpha3: 'ZWL',
        numeric: '932',
        minor: 2,
    },
];

let i;
for (i = 0; i < list.length; i++) {
    list[i] = Object.freeze(list[i]);
}

module.exports = Object.freeze(list);
